### ISSUE TITLE
Max time exercise bug?! 

### ISSUE THREAD

**Issue by Adito5393** [groothuisss/HIITtoget-Issues-and-Features#2]
Before starting the session, a max time can be set:
<img src="https://user-images.githubusercontent.com/39572144/111700924-5de98d80-883a-11eb-86cb-8bd2aede5e1e.jpg" width="50%">
However, once the session starts, the max time is higher:
<img src="https://user-images.githubusercontent.com/39572144/111700979-6e016d00-883a-11eb-8015-c7587a6b9533.jpg" width="50%">

Is this how it should work?

**Comment by groothuisss** [comment]
Thanks for mentioning this. It is indeed how it should work. The time that you can set up is the maximum time that you can spend on the intervals part of the session, excluding warming up and cooling down. Before going into the session you can press "Summary" at the bottom, to see how you currently have set up the training.

I will change the name of that slider though to something like "Maximum time for intervals" or so, to make it clearer.

**Comment by groothuisss** [comment]
By the way, the little (i) next to "EXERCISE CRITERIA" gives information on what everything does. Maybe it's not clear enough that that is an info dialog?

**Comment by Adito5393** [comment]
The (i) symbol is clear enough that if clicked will provide more info on the topic. 

The last sentence of the "EXERCISE CRITERIA" says: "This prevents an exercise session from taking longer than a desired max duration." and this is not true with the current implementation. I would love to be implemented this way, because as a simple user I only have, let's say 30min and I don't really wanna do trial and error (if the user would be bad at simple math 😃 ) and modify it such that the summary shows 30min.

Mainly, I think that using the max time criteria should not require any additional info, by default.

**Comment by groothuisss** [comment]
Thanks for the comment! Hmm, it's a tough point that has cost me quite some thinking during the development. I will reconsider this indeed. No promises though. 😄 

In principle the goal of such an interval exercising session is that a certain time at %Vo2max is spent, without needing to exercise for a long duration to get training benefits. So users are encouraged to not set those kind of time limits and just do what gives the optimal training benefit as estimated by the app's algorithm. Therefore maximum duration is deselected by default. Of course it's a nice feature to constrain exercising duration to a user's available time, which is why it is implemented.

UI/UX wise it seems an easy change/fix, but technically there is a bit more going on under water that complicates such a change. Maybe as an intermediate solution I can print the estimated total training time immediately below the intervals time limit slider, so the feedback loop to the user is shorter.

**Comment by Adito5393** [comment]
Good job with the latest update!! 

Feel free to close this issue as I think, with the latest version 0.5.19, the max time is clear now:

<img src="https://user-images.githubusercontent.com/39572144/115104221-4267c480-9f57-11eb-96b0-090ca41f4f5a.jpg" width="50%">

**Comment by groothuisss** [comment]
Awesome, happy that you like it! I can still keep it in mind, but I guess for now the solution suffices. Cheers!
