### ISSUE TITLE
Garmin watch app support

### ISSUE THREAD

**Issue by Adito5393** [groothuisss/HIITtoget-Issues-and-Features#3]
What are your plans regarding the integration of the app with a Garmin smartwatch? 

At the moment, it is a bit annoying to have to run with the phone and I would love to contribute to making an app for the Garmin watch. I plan to buy a Garmin watch in the future, however, at the moment I could develop the app and test it on a Garmin 245 Music (owned by Rosana 😄 ).

I found the following resources that could speed up the development of such a Garmin app:

1. [A collection of Connect IQ apps and libraries](https://github.com/garmin/connectiq-apps) - officially maintained by Garmin
2. [Example apps with src code](https://starttorun.info/connect-iq-apps-with-source-code/) to see how certain functionalities are implemented to use Garmin SDK

**Comment by groothuisss** [comment]
It was not really on my radar to develop an app that runs on a watch, but it all depends on whether it can be done given the nature of this app, how much time it costs, and how large "the market" is for that. How does it normally work actually? You start the app on the phone, make the settings, and as soon as you want to start exercising you push that program to the watch or so? Then when the training is done the results get pushed back to the phone and the normal flow and controls are picked up again on the phone? I am surely curious to find out more! :)

Currently an iOS version of the app has a higher priority, but to accomodate users of a smartwatch I will implement (in the near future) notifications that should be visible on the watch to show in which interval you currently are including controls to skip an interval. This way a phone can at least be put in a pocket instead of having it in view.

**Comment by Adito5393** [comment]
The notification idea would be easier to implement and maintain for a wider variety of devices (WearOS, Garmin, etc.).

Regarding the stand-alone watch app, that's exactly the use case I was thinking to keep it simple: the user would make all the configuration as normally he does, but instead of the "Enter Session" button, he can "Export to Garmin". The Garmin device would receive the most simplified form of the formula that needs to be calculated with the only dynamic variable being the heart rate value.

Looking at the Garmin SDK, we should first decide on which type of application we will develop. Here are my thoughts on the [4 options](https://developer.garmin.com/connect-iq/user-experience-guidelines/app-types/) available:

1. ~~Watch face~~ - no need to be running 24/7
1. Data field - the biggest advantage of this is that it binds to activities (and the user during the activity can choose to see other info like speed, map, etc), however, "Data fields do not accept input" and I think this means we can't input the formula from the phone app.
1. ~~Widgets~~ - according to [this](https://forums.garmin.com/developer/connect-iq/f/discussion/1199/using-widget-during-activity), Garmin does not allow the use of custom widgets during an activity; which is exactly how a user would like to use it, e.g. during running activity.
1. Device Apps - would mean that the user can not run any other activity, therefore, this app should fully replace whatever activity/app otherwise the user would use. That can be anything since HIIT can be done while doing any sports activity. 

Garmin apps are developed using [Monkey C](https://developer.garmin.com/connect-iq/monkey-c/) and [here](https://developer.garmin.com/connect-iq/monkey-c/objects-and-memory/) (see the sub-chapter **APIs and App Types**) is the table with which modules are accessible for which application type. 

I will look more into the Data field apps documentation, to see if and how it can accept input a formula to store and use.

**Comment by groothuisss** [comment]
Currently notification support has been implemented which also works on smart watches. The notifications have buttons on the smart phone, which become selectable actions on the smart watch. This way intervals can be skipped or paused/resumed, and the training can be stopped, all while keeping your smart phone in your pocket.

If this works well enough in general I will leave it with that for now and possibly pick up this issue in the future to have native/dedicated smart watch support. Therefore, I'll close this issue for now.
